### ISSUE TITLE
Failed to run tests using "Ledger dev tools"

### ISSUE THREAD

**Issue by mbaranovski** [LedgerHQ/app-plugin-boilerplate#127]
Hi!

I installed the Ledger dev tools plugin, then:
1. Downloaded the docker image inside a fresh `app-plugin-boilerplate`
2. Clicked "Build" on the extension which successfully finished
<img width="931" alt="CleanShot 2024-01-03 at 16 52 48@2x" src="https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/31d6c549-9079-4808-bc99-dd912f2ec1f3">
3. Clicked on "Run tests" which failed with:
<img width="1288" alt="CleanShot 2024-01-03 at 16 53 33@2x" src="https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/027d1c1e-f929-4566-9215-c0fe296e874e">
4. Tried to go around the problem and I docker execed into the container and ran `cp -R build/ ./tests/ethereum_build/`
5. Tests executed but failed with
<img width="1295" alt="CleanShot 2024-01-03 at 16 55 20@2x" src="https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/4de31e67-41f1-491d-83c2-a1f8a6d5be0c">
<img width="1042" alt="CleanShot 2024-01-03 at 16 55 31@2x" src="https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/1f302017-a1c4-4993-91b9-443b4f8f1b5e">

Please suggest the steps forward, we want to release our app in the Ledger Live. Thank you!

**Comment by adrienlacombe** [comment]
which OS are you on?

**Comment by mbaranovski** [comment]
I'm on MacOS. Okay I solved the problem and successfully ran the tests. Steps:
1. Install X11
2. Modify X11 security settings as follows
<img width="484" alt="CleanShot 2024-01-03 at 18 35 03@2x" src="https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/d3b43011-71fb-43db-a09e-f46b3f5d1e9c">

3. Restart X11 (important)
4. Run: `xhost +local:docker` in the terminal
5. Download the ethereum app artifacts (building via VS extension for all targets and copying it to the tests folder was still complaining that cannot find Ethereum app)
![CleanShot 2024-01-03 at 18 36 49@2x](https://github.com/LedgerHQ/app-plugin-boilerplate/assets/29602306/bb492403-90a2-4597-a540-e044315612fe)
6. `Run tests` via VS code extension
