### ISSUE TITLE
Timeout waiting to connect

### ISSUE THREAD

**Issue by LateNightMoods** [LedgerHQ/app-plugin-boilerplate#28]
![image](https://user-images.githubusercontent.com/71435890/177742957-d23cf489-220f-4496-8313-4743bcaa18ca.png)

I want to render this `value`, but I don't see any instructions for this in the documentation.

try to get it in the following way, but an error is reported.

`handle_provide_parameter.c`
```C
...
switch (context->next_param) {
        case MIN_AMOUNT_RECEIVED:
            copy_parameter(context->amount_pay,
                            msg->pluginSharedRO->txContent->value.value,
                            sizeof(context->amount_pay));
            copy_parameter(context->amount_received,
                           msg->parameter,
                           sizeof(context->amount_received));
            context->next_param = UNEXPECTED_PARAMETER;
            break;
        // ...
        default:
            PRINTF("Param not supported: %d\n", context->next_param);
            msg->result = ETH_PLUGIN_RESULT_ERROR;
            break;
}
```
`handle_query_contract_ui.c`
```C
// ...
amountToString(context->amount_pay, sizeof(context->amount_pay), decimals, ticker, msg->msg, msg->msgLength);
// ...
```

`xxx.test.js`
```JavaScript
// ...
unsignedTx.value = parseEther("0.0009");
// ...
```
![image](https://user-images.githubusercontent.com/71435890/177748426-38078f94-4027-4c39-a692-6be99de667e2.png)

**Comment by adrienlacombe-ledger** [comment]
This value is always displayed

**Comment by LateNightMoods** [comment]
Thanks Reply.

I shouldn't use `sizeof`.

used `msg->pluginSharedRO->txContent->value.length` to get the length, which solved the error.

**Comment by adrienlacombe-ledger** [comment]
Glad to hear that! Sorry I thought it was always displayed but actually no.
