### ISSUE TITLE
Tests issues related to missing func

### ISSUE THREAD

**Issue by emmanuelm41** [LedgerHQ/app-plugin-boilerplate#5]
It seems tests are broken because of the lack of a function on **@LedgerHQ/hw-app-eth**. The function it says is not defined is **setPluginsLoadConfig**.

The failure happens here more precisely
https://github.com/LedgerHQ/app-plugin-boilerplate/blob/ec1cc4ea621402c554ba585ef95206200d91e6d5/tests/src/test.fixture.js#L101

I have tried to update the package to the last version, but it wasn't work. The actual version is  6.7.0 and the last one is 6.18.0.

**Comment by emmanuelm41** [comment]
The fix is this one:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/10941036/144439995-d21c24a5-02ec-4cdf-88eb-c4784c6f9f4e.png">

**Comment by TamtamHero** [comment]
Fixed in https://github.com/LedgerHQ/app-plugin-boilerplate/commit/00213197b86379af745cea3662bfa23e7bededc5, thank you !
