### ISSUE TITLE
Nano X build process fails with latest builder image

### ISSUE THREAD

**Issue by emmanuelm41** [LedgerHQ/app-plugin-boilerplate#6]
The nano x build process is broken if you use the [latest version](https://github.com/LedgerHQ/ledger-app-builder/pkgs/container/ledger-app-builder%2Fledger-app-builder/10201603?tag=sha-ac0e0e5) of container image.
<img width="998" alt="image" src="https://user-images.githubusercontent.com/10941036/144449149-6541e913-4775-4425-8038-77759a3efe54.png">

If you use [this version](https://github.com/LedgerHQ/ledger-app-builder/pkgs/container/ledger-app-builder%2Fledger-app-builder/9408428?tag=sha-ae07d3c), it works. That version was used on [this CI job](https://github.com/LedgerHQ/app-plugin-boilerplate/runs/4188651743?check_suite_focus=true).

**Comment by alacombe-ledger** [comment]
Thank you @emmanuelm41 please let us know if https://github.com/LedgerHQ/app-plugin-boilerplate/commit/0bf8fa07ae700e5773f38b7830e109cc41073e20 fixed this issue or not.

**Comment by emmanuelm41** [comment]
The building process is working now indeed. I think you could update Ethereum sdk submodule version on repo and it should be ready. However, the other two issues I created are still there despite of this improvement.

**Comment by alacombe-ledger** [comment]
I agree

**Comment by emmanuelm41** [comment]
After doing it, please close the issue!!
